export const BLOCKWORDS_REQUEST = "BLOCKWORDS_REQUEST";
export const BLOCKWORDS_SUCCESS = "BLOCKWORDS_SUCCESS";
export const BLOCKWORDS_FAIL = "BLOCKWORDS_FAIL";

export const GETALL_BLOCKWORDS_REQUEST = "GETALL_BLOCKWORDS_REQUEST";
export const GETALL_BLOCKWORDS_SUCCESS = "GETALL_BLOCKWORDS_SUCCESS";
export const GETALL_BLOCKWORDS_FAIL = "GETALL_BLOCKWORDS_FAIL";

export const UPDATE_BLOCKWORDS_REQUEST = "UPDATE_BLOCKWORDS_REQUEST";
export const UPDATE_BLOCKWORDS_SUCCESS = "UPDATE_BLOCKWORDS_SUCCESS";
export const UPDATE_BLOCKWORDS_FAIL = "UPDATE_BLOCKWORDS_FAIL";
