export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAIL = "CATEGORY_FAIL";



export const ALL_CATEGORY_REQUEST = "ALL_CATEGORY_REQUEST";
export const ALL_CATEGORY_SUCCESS = "ALL_CATEGORY_SUCCESS";
export const ALL_CATEGORY_FAIL = "ALL_CATEGORY_FAIL";



//*********sub-category section *************** */

export const SUB_CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const SUB_CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const SUB_CATEGORY_FAIL = "CATEGORY_FAIL";



export const ALL_SUB_CATEGORY_REQUEST = "ALL_CATEGORY_REQUEST";
export const ALL_SUB_CATEGORY_SUCCESS = "ALL_CATEGORY_SUCCESS";
export const ALL_SUB_CATEGORY_FAIL = "ALL_CATEGORY_FAIL";
