export const DAILYQUIZ_REQUEST = "DAILYQUIZ_REQUEST";
export const DAILYQUIZ_SUCCESS = "DAILYQUIZ_SUCCESS";
export const DAILYQUIZ_FAIL = "DAILYQUIZ_FAIL";

export const GET_DAILYQUIZ_REQUEST = "GET_DAILYQUIZ_REQUEST";
export const GET_DAILYQUIZ_SUCCESS = "GET_DAILYQUIZ_SUCCESS";
export const GET_DAILYQUIZ_FAIL = "GET_DAILYQUIZ_FAIL";