export const DAILYTIPS_REQUEST = "DAILYTIPS_REQUEST";
export const DAILYTIPS_SUCCESS = "DAILYTIPS_SUCCESS";
export const DAILYTIPS_FAIL = "DAILYTIPS_FAIL";

export const ALL_DAILYTIPS_REQUEST = "ALL_DAILYTIPS_REQUEST";
export const ALL_DAILYTIPS_SUCCESS = "ALL_DAILYTIPS_SUCCESS";
export const ALL_DAILYTIPS_FAIL = "ALL_DAILYTIPS_FAIL";

export const UPDATE_DAILYTIPS_REQUEST = "UPDATE_DAILYTIPS_REQUEST";
export const UPDATE_DAILYTIPS_SUCCESS = "UPDATE_DAILYTIPS_SUCCESS";
export const UPDATE_DAILYTIPS_FAIL = "UPDATE_DAILYTIPS_FAIL";