export const EXERCISE_REQUEST = "EXERCISE_REQUEST";
export const EXERCISE_SUCCESS = "EXERCISE_SUCCESS";
export const EXERCISE_FAIL = "EXERCISE_FAIL";

export const GETALL_EXERCISE_REQUEST = "GETALL_EXERCISE_REQUEST";
export const GETALL_EXERCISE_SUCCESS = "GETALL_EXERCISE_SUCCESS";
export const GETALL_EXERCISE_FAIL = "GETALL_EXERCISE_FAIL";

export const UPDATE_EXERCISE_REQUEST = "UPDATE_EXERCISE_REQUEST";
export const UPDATE_EXERCISE_SUCCESS = "UPDATE_EXERCISE_SUCCESS";
export const UPDATE_EXERCISE_FAIL = "UPDATE_EXERCISE_FAIL";