export const INTREST_REQUEST = "INTREST_REQUEST";
export const INTREST_SUCCESS = "INTREST_SUCCESS";
export const INTREST_FAIL = "INTREST_FAIL";

export const GETALL_INTREST_REQUEST = "GETALL_INTREST_REQUEST";
export const GETALL_INTREST_SUCCESS = "GETALL_INTREST_SUCCESS";
export const GETALL_INTREST_FAIL = "GETALL_INTREST_FAIL";

export const INTREST_REQUEST_UPDATE = "INTREST_REQUEST_UPDATE";
export const INTREST_SUCCESS_UPDATE = "INTREST_SUCCESS_UPDATE";
export const INTREST_FAIL_UPDATE = "INTREST_FAIL_UPDATE";